//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sleep.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sleep.Exceptions.ResourceMessageException", typeof(ResourceMessageException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The alcohol field can&apos;t be null..
        /// </summary>
        public static string ALCOHOL_NOT_NULL {
            get {
                return ResourceManager.GetString("ALCOHOL_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The blood pressure cant be empty..
        /// </summary>
        public static string BLOOD_PRESSURE_EMPTY {
            get {
                return ResourceManager.GetString("BLOOD_PRESSURE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The BMI is invalid..
        /// </summary>
        public static string BMI_INVALID {
            get {
                return ResourceManager.GetString("BMI_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The caffeine field can&apos;t be null..
        /// </summary>
        public static string CAFFEINE_NOT_NULL {
            get {
                return ResourceManager.GetString("CAFFEINE_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The daily steps cannot be empty..
        /// </summary>
        public static string DAILY_STEPS_EMPTY {
            get {
                return ResourceManager.GetString("DAILY_STEPS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail already registered..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The E-mail cannot be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The E-mail is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email or password is incorret..
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The end date can&apos;t be greater than start date..
        /// </summary>
        public static string END_DATE_GREATER_THAN_START {
            get {
                return ResourceManager.GetString("END_DATE_GREATER_THAN_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The gender is invalid..
        /// </summary>
        public static string GENDER_INVALID {
            get {
                return ResourceManager.GetString("GENDER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The heart rate cannot be empty..
        /// </summary>
        public static string HEART_RATE_EMPTY {
            get {
                return ResourceManager.GetString("HEART_RATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The name cannot be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Occupation cannot be empty..
        /// </summary>
        public static string OCCUPATION_EMPTY {
            get {
                return ResourceManager.GetString("OCCUPATION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password is invalid..
        /// </summary>
        public static string PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The physical activity cant be empty..
        /// </summary>
        public static string PHYSICAL_ACTIVY_MINUTES_NOT_EMPTY {
            get {
                return ResourceManager.GetString("PHYSICAL_ACTIVY_MINUTES_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The date already exists..
        /// </summary>
        public static string RECORD_DATE_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("RECORD_DATE_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The record date can&apos;t be null..
        /// </summary>
        public static string RECORD_DATE_NULL {
            get {
                return ResourceManager.GetString("RECORD_DATE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The screen before sleep can&apos;t be null..
        /// </summary>
        public static string SCREEN_BEFORE_SLEEP_NULL {
            get {
                return ResourceManager.GetString("SCREEN_BEFORE_SLEEP_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The sleep disorder is invalid.
        /// </summary>
        public static string SLEEP_DISORDER_INVALID {
            get {
                return ResourceManager.GetString("SLEEP_DISORDER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The date can&apos;t be lesser than start..
        /// </summary>
        public static string SLEEP_END_DATE_LESS_THAN_START {
            get {
                return ResourceManager.GetString("SLEEP_END_DATE_LESS_THAN_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknow error..
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value has to be between 1 and 10..
        /// </summary>
        public static string VALUE_BETWEEN_1_10 {
            get {
                return ResourceManager.GetString("VALUE_BETWEEN_1_10", resourceCulture);
            }
        }
    }
}
